// Generated by gencpp from file sensor_math/CustomIMUMsg.msg
// DO NOT EDIT!


#ifndef SENSOR_MATH_MESSAGE_CUSTOMIMUMSG_H
#define SENSOR_MATH_MESSAGE_CUSTOMIMUMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sensor_math
{
template <class ContainerAllocator>
struct CustomIMUMsg_
{
  typedef CustomIMUMsg_<ContainerAllocator> Type;

  CustomIMUMsg_()
    : header()
    , acceleration()
    , gyroscope()
    , magnetometer()  {
      acceleration.assign(0.0);

      gyroscope.assign(0.0);

      magnetometer.assign(0.0);
  }
  CustomIMUMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , acceleration()
    , gyroscope()
    , magnetometer()  {
  (void)_alloc;
      acceleration.assign(0.0);

      gyroscope.assign(0.0);

      magnetometer.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 3>  _acceleration_type;
  _acceleration_type acceleration;

   typedef boost::array<float, 3>  _gyroscope_type;
  _gyroscope_type gyroscope;

   typedef boost::array<float, 3>  _magnetometer_type;
  _magnetometer_type magnetometer;





  typedef boost::shared_ptr< ::sensor_math::CustomIMUMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_math::CustomIMUMsg_<ContainerAllocator> const> ConstPtr;

}; // struct CustomIMUMsg_

typedef ::sensor_math::CustomIMUMsg_<std::allocator<void> > CustomIMUMsg;

typedef boost::shared_ptr< ::sensor_math::CustomIMUMsg > CustomIMUMsgPtr;
typedef boost::shared_ptr< ::sensor_math::CustomIMUMsg const> CustomIMUMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_math::CustomIMUMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_math::CustomIMUMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_math::CustomIMUMsg_<ContainerAllocator1> & lhs, const ::sensor_math::CustomIMUMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.acceleration == rhs.acceleration &&
    lhs.gyroscope == rhs.gyroscope &&
    lhs.magnetometer == rhs.magnetometer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_math::CustomIMUMsg_<ContainerAllocator1> & lhs, const ::sensor_math::CustomIMUMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_math

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_math::CustomIMUMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_math::CustomIMUMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_math::CustomIMUMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_math::CustomIMUMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_math::CustomIMUMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_math::CustomIMUMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_math::CustomIMUMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5caa9162e195ad161e6e93fe1f83380";
  }

  static const char* value(const ::sensor_math::CustomIMUMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5caa9162e195ad1ULL;
  static const uint64_t static_value2 = 0x61e6e93fe1f83380ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_math::CustomIMUMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_math/CustomIMUMsg";
  }

  static const char* value(const ::sensor_math::CustomIMUMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_math::CustomIMUMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#CustomIMUMsg.msg\n"
"Header header\n"
"\n"
"float32[3] acceleration \n"
"float32[3] gyroscope\n"
"float32[3] magnetometer\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sensor_math::CustomIMUMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_math::CustomIMUMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.acceleration);
      stream.next(m.gyroscope);
      stream.next(m.magnetometer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomIMUMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_math::CustomIMUMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_math::CustomIMUMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "acceleration[]" << std::endl;
    for (size_t i = 0; i < v.acceleration.size(); ++i)
    {
      s << indent << "  acceleration[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.acceleration[i]);
    }
    s << indent << "gyroscope[]" << std::endl;
    for (size_t i = 0; i < v.gyroscope.size(); ++i)
    {
      s << indent << "  gyroscope[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gyroscope[i]);
    }
    s << indent << "magnetometer[]" << std::endl;
    for (size_t i = 0; i < v.magnetometer.size(); ++i)
    {
      s << indent << "  magnetometer[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.magnetometer[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_MATH_MESSAGE_CUSTOMIMUMSG_H
